AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  elastic-serverless-forwarder

  SAM Template for elastic-serverless-forwarder

Resources:
  ElasticServerlessForwarderContinuingDLQ:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: 0
      QueueName: !Join [ "-", ["elastic-serverless-forwarder-continuing-dlq", !Select [4, !Split ['-', !Select [2, !Split ['/', !Ref AWS::StackId]]]]]]
      VisibilityTimeout: 910
  ElasticServerlessForwarderContinuingQueue:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: 0
      QueueName: !Join [ "-", ["elastic-serverless-forwarder-continuing-queue", !Select [4, !Split ['-', !Select [2, !Split ['/', !Ref AWS::StackId]]]]]]
      RedrivePolicy: { "deadLetterTargetArn" : !GetAtt ElasticServerlessForwarderContinuingDLQ.Arn, "maxReceiveCount" : 1 }
      VisibilityTimeout: 910
  ElasticServerlessForwarderReplayDLQ:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: 0
      QueueName: !Join [ "-", ["elastic-serverless-forwarder-replay-dlq", !Select [4, !Split ['-', !Select [2, !Split ['/', !Ref AWS::StackId]]]]]]
      VisibilityTimeout: 910
  ElasticServerlessForwarderReplayQueue:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: 0
      QueueName: !Join [ "-", ["elastic-serverless-forwarder-replay-queue", !Select [4, !Split ['-', !Select [2, !Split ['/', !Ref AWS::StackId]]]]]]
      RedrivePolicy: { "deadLetterTargetArn" : !GetAtt ElasticServerlessForwarderReplayDLQ.Arn, "maxReceiveCount" : 3 }
      VisibilityTimeout: 910
  ElasticServerlessForwarderFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 900
      MemorySize: 512
      CodeUri: %codeUri%
      Runtime: python3.9
      Architectures:
        - x86_64
      Handler: main_aws.handler
      Environment:
          Variables:
              S3_CONFIG_FILE: "s3://"
              SQS_CONTINUE_URL: !Ref ElasticServerlessForwarderContinuingQueue
              SQS_REPLAY_URL: !Ref ElasticServerlessForwarderReplayQueue
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt ElasticServerlessForwarderContinuingQueue.Arn
            BatchSize: 10
            Enabled: true
Metadata:
  AWS::ServerlessRepo::Application:
    Name: %sarAppName%
    Description: Send observability data from your AWS environment to Elastic.
    Author: %sarAuthorName%
    Labels: ['s3', 'logs', 'analytics', 'observability', 'monitoring', 'Elastic']
    SemanticVersion: %semanticVersion%
    LicenseUrl: .aws-sam/build/ElasticServerlessForwarderFunction/LICENSE.txt
    ReadmeUrl: .aws-sam/build/ElasticServerlessForwarderFunction/README.md
    HomePageUrl: https://github.com/elastic/elastic-serverless-forwarder
    SourceCodeUrl: https://github.com/elastic/elastic-serverless-forwarder
