AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  elastic-serverless-forwarder

  SAM Template for elastic-serverless-forwarder

Resources:
  ElasticServerlessForwarderContinuingDLQ:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: 0
      QueueName: !Join [ "-", ["elastic-serverless-forwarder-continuing-dlq", !Select [4, !Split ['-', !Select [2, !Split ['/', !Ref AWS::StackId]]]]]]
      VisibilityTimeout: 900
  ElasticServerlessForwarderContinuingQueue:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: 0
      QueueName: !Join [ "-", ["elastic-serverless-forwarder-continuing-queue", !Select [4, !Split ['-', !Select [2, !Split ['/', !Ref AWS::StackId]]]]]]
      RedrivePolicy: { "deadLetterTargetArn" : !GetAtt ElasticServerlessForwarderContinuingDLQ.Arn, "maxReceiveCount" : 1 }
      VisibilityTimeout: 900
  ElasticServerlessForwarderFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 900
      MemorySize: 128
      PackageType: Zip
      CodeUri:
        Bucket: %codeURIBucket%
        Key: lambda.zip
      Runtime: python3.9
      Handler: main_aws.handler
      Environment:
          Variables:
              SQS_CONTINUE_URL: !Ref ElasticServerlessForwarderContinuingQueue
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt ElasticServerlessForwarderContinuingQueue.Arn
            BatchSize: 1
            Enabled: true
      Policies:
      - AWSLambdaExecute # Managed Policy
      - Version: '2012-10-17' # Policy Document
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
            Resource: 'arn:aws:s3:::*/*'
      - Version: '2012-10-17' # Policy Document
        Statement:
          - Effect: Allow
            Action:
              - sqs:ReceiveMessage
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
            Resource: 'arn:aws:sqs:*:*:*'
Metadata:
  AWS::ServerlessRepo::Application:
    Name: elastic-serverless-forwarder
    Description: Elastic Forwared for Serverless
    Author: elastic
    SemanticVersion: 0.11.2
    LicenseUrl: LICENSE.txt
    ReadmeUrl: README.md
    HomePageUrl: https://github.com/elastic/elastic-serverless-forwarder
